version: "3.8"

services:
  arcademy-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: arcademy-db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Your_Password123"
    ports:
      - "1433:1433"
    volumes:
      - arcademy-db-data:/var/opt/mssql

volumes:
  arcademy-db-data:
